export const LOGIN_START = 'LOGIN_START'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const SIGNUP_START = 'SIGNUP_START'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'

export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS'
export const FETCH_POST_FAIL = 'FETCH_POST_FAIL'

export const FAVOURITE_POSTS = 'FAVOURITE_POSTS'

export const NEW_POST_SUCCESS = 'NEW_POST_SUCCESS'
export const NEW_POST_START = 'NEW_POST_START'
export const NEW_POST_FAIL = 'NEW_POST_FAIL'

export const FETCH_MYPOSTS_SUCCESS = 'FETCH_MYPOSTS_SUCCESS'